/* Core — plant ids, persisted edits (localStorage), shared lookups.
   PLANTS and K are provided by js/data.js, generated by Gulp from /data. */
PLANTS.forEach((p, i) => (p.__id = i));
/* Apply any locally-saved edits over the embedded data */
let EDITS = {};
try {
  EDITS = JSON.parse(localStorage.getItem('plantEdits') || '{}');
} catch (e) {
  EDITS = {};
}
function applyEdits() {
  for (const id in EDITS) {
    const p = PLANTS[id];
    if (!p) continue;
    for (const k in EDITS[id]) p[k] = EDITS[id][k];
  }
}
applyEdits();
function persistEdits() {
  try {
    localStorage.setItem('plantEdits', JSON.stringify(EDITS));
  } catch (e) {}
}
function editCount() {
  return Object.keys(EDITS).length;
}
const POLL_KEY = (() => {
  for (const p of PLANTS) for (const k in p) if (k.includes('Pollinators Supported')) return k;
  return '';
})();
